[2024-07-17T08:58:30.580+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T08:58:30.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T08:58:22.055468+00:00 [queued]>
[2024-07-17T08:58:30.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T08:58:22.055468+00:00 [queued]>
[2024-07-17T08:58:30.626+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T08:58:30.653+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parse_data> on 2024-07-17 08:58:22.055468+00:00
[2024-07-17T08:58:30.667+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parse_data_dag', 'parse_data', 'manual__2024-07-17T08:58:22.055468+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/parsing_dag.py', '--cfg-path', '/tmp/tmppi0yqfkf']
[2024-07-17T08:58:30.665+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T08:58:30.669+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask parse_data
[2024-07-17T08:58:30.669+0000] {standard_task_runner.py:64} INFO - Started process 86 to run task
[2024-07-17T08:58:30.731+0000] {task_command.py:426} INFO - Running <TaskInstance: parse_data_dag.parse_data manual__2024-07-17T08:58:22.055468+00:00 [running]> on host 1254a1bc6f0b
[2024-07-17T08:58:30.835+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_data_dag' AIRFLOW_CTX_TASK_ID='parse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T08:58:22.055468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T08:58:22.055468+00:00'
[2024-07-17T08:58:30.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T08:58:41.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T08:58:41.168+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_dag.py", line 127, in parse_data
    result_in_city = process_table(driver, options_in_city)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_dag.py", line 53, in process_table
    buy_rate_button.click()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x5616bed19ca7 <unknown>
#1 0x5616be9f09aa <unknown>
#2 0x5616bea37590 <unknown>
#3 0x5616bea2cf1a <unknown>
#4 0x5616bea57f86 <unknown>
#5 0x5616bea2c912 <unknown>
#6 0x5616bea58132 <unknown>
#7 0x5616bea74f16 <unknown>
#8 0x5616bea57ce7 <unknown>
#9 0x5616bea2a6b1 <unknown>
#10 0x5616bea2b4c6 <unknown>
#11 0x5616bece755a <unknown>
#12 0x5616becea8ea <unknown>
#13 0x5616becea393 <unknown>
#14 0x5616becead79 <unknown>
#15 0x5616becd7b2f <unknown>
#16 0x5616beceb134 <unknown>
#17 0x5616becc05aa <unknown>
#18 0x5616bed0a459 <unknown>
#19 0x5616bed0a646 <unknown>
#20 0x5616bed19193 <unknown>
#21 0x7f11f3a40134 <unknown>

[2024-07-17T08:58:41.191+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parse_data_dag, task_id=parse_data, run_id=manual__2024-07-17T08:58:22.055468+00:00, execution_date=20240717T085822, start_date=20240717T085830, end_date=20240717T085841
[2024-07-17T08:58:41.213+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task parse_data (Message: element not interactable
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x5616bed19ca7 <unknown>
#1 0x5616be9f09aa <unknown>
#2 0x5616bea37590 <unknown>
#3 0x5616bea2cf1a <unknown>
#4 0x5616bea57f86 <unknown>
#5 0x5616bea2c912 <unknown>
#6 0x5616bea58132 <unknown>
#7 0x5616bea74f16 <unknown>
#8 0x5616bea57ce7 <unknown>
#9 0x5616bea2a6b1 <unknown>
#10 0x5616bea2b4c6 <unknown>
#11 0x5616bece755a <unknown>
#12 0x5616becea8ea <unknown>
#13 0x5616becea393 <unknown>
#14 0x5616becead79 <unknown>
#15 0x5616becd7b2f <unknown>
#16 0x5616beceb134 <unknown>
#17 0x5616becc05aa <unknown>
#18 0x5616bed0a459 <unknown>
#19 0x5616bed0a646 <unknown>
#20 0x5616bed19193 <unknown>
#21 0x7f11f3a40134 <unknown>
; 86)
[2024-07-17T08:58:41.251+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-17T08:58:41.268+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T08:58:41.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
