[2024-07-17T10:22:00.776+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T10:22:00.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T10:21:54.797319+00:00 [queued]>
[2024-07-17T10:22:00.840+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T10:21:54.797319+00:00 [queued]>
[2024-07-17T10:22:00.841+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T10:22:00.866+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parse_data> on 2024-07-17 10:21:54.797319+00:00
[2024-07-17T10:22:00.885+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T10:22:00.889+0000] {standard_task_runner.py:64} INFO - Started process 86 to run task
[2024-07-17T10:22:00.886+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parse_data_dag', 'parse_data', 'manual__2024-07-17T10:21:54.797319+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/parsing_dag.py', '--cfg-path', '/tmp/tmpc20mx9iz']
[2024-07-17T10:22:00.892+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask parse_data
[2024-07-17T10:22:00.998+0000] {task_command.py:426} INFO - Running <TaskInstance: parse_data_dag.parse_data manual__2024-07-17T10:21:54.797319+00:00 [running]> on host 1254a1bc6f0b
[2024-07-17T10:22:01.208+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_data_dag' AIRFLOW_CTX_TASK_ID='parse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T10:21:54.797319+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T10:21:54.797319+00:00'
[2024-07-17T10:22:01.221+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T10:22:13.957+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T10:22:13.958+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_dag.py", line 132, in parse_data
    result_in_city = process_table1(in_city_table, options_in_city, result_in_city)
                     ^^^^^^^^^^^^^^
NameError: name 'process_table1' is not defined. Did you mean: 'process_table'?
[2024-07-17T10:22:13.987+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parse_data_dag, task_id=parse_data, run_id=manual__2024-07-17T10:21:54.797319+00:00, execution_date=20240717T102154, start_date=20240717T102200, end_date=20240717T102213
[2024-07-17T10:22:14.015+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task parse_data (name 'process_table1' is not defined; 86)
[2024-07-17T10:22:14.042+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-17T10:22:14.075+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T10:22:14.078+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
